name: automated_testing_framework_plugin_sqflite
description: Library to use SQLite Database as a storage mechanism for automated tests and test results.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  automated_testing_framework: ^1.1.0
  convert: ^2.1.1
  sqflite: ^1.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
