name: automated_testing_framework_plugin_sqflite
description: Library to use SQLite Database as a storage mechanism for automated tests and test results.
homepage: https://github.com/limonadev/automated_testing_framework_plugin_sqflite

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  automated_testing_framework: 1.2.6+3
  convert: ^2.1.1
  logging: ^0.11.4
  sqflite: ^1.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
